### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by sunilsankar** [andrexus/terraform-provider-proxmox#1]
Hi when I compile this . I get the below error how do I solve this
[root@gitlab-runner terraform-provider-proxmox]# go build -o terraform-provider-proxmox# github.com/andrexus/terraform-provider-proxmox/proxmox
proxmox/resource_vm.go:47:12: undefined: goproxmox.NewVMConfig
proxmox/resource_vm.go:53:31: too many arguments in call to client.VMs.CreateVM
proxmox/resource_vm.go:69:27: client.VMs.GetVMConfig undefined (type goproxmox.QemuService has no field or method GetVMConfig)
proxmox/resource_vm.go:85:12: undefined: goproxmox.NewVMConfig
proxmox/resource_vm.go:92:22: client.VMs.UpdateVM undefined (type goproxmox.QemuService has no field or method UpdateVM)
[root@gitlab-runner terraform-provider-proxmox]#

**Comment by andrexus** [comment]
should be resolved now

**Comment by sunilsankar** [comment]
Still getting the same error andrexus. Can you please tell me how to compile this

[root@gitlab-runner terraform-provider-proxmox]# go build -o terraform-provider-proxmox
# github.com/andrexus/terraform-provider-proxmox/proxmox
proxmox/resource_vm.go:47:12: undefined: goproxmox.NewVMConfig
proxmox/resource_vm.go:73:24: config.GetName undefined (type *goproxmox.VMConfig has no field or method GetName)
proxmox/resource_vm.go:85:12: undefined: goproxmox.NewVMConfig
[root@gitlab-runner terraform-provider-proxmox]#

**Comment by andrexus** [comment]
@sunilsankar you can download compiled binaries from [releases](https://github.com/andrexus/terraform-provider-proxmox/releases) page
